Add temporary workaround to rerun the installation if it fails for a first time

diff --git a/playbooks/satellite/roles/setup/tasks/main.yaml b/playbooks/satellite/roles/setup/tasks/main.yaml
--- a/playbooks/satellite/roles/setup/tasks/main.yaml
+++ b/playbooks/satellite/roles/setup/tasks/main.yaml
@@ -102,8 +102,13 @@
       sat_installer_options: "--foreman-initial-admin-email {{ sat_email }} --foreman-initial-admin-username {{ sat_user }} --foreman-initial-admin-password {{ sat_pass }}"
     when: "sat_version is version('6.6', '>=')"
   - name: "Satellite configured"
-    command:
-      "{{ sat_installer_cmd }} {{ sat_installer_options }}"
+    shell: |
+      {{ sat_installer_cmd }} {{ sat_installer_options }}
+      if [ $? -ne 0 -a $( date +%s ) -lt $( date -d "2020-10-10" +%s ) ]; then
+          echo "INFO: Previous installation attempt failed, trying again"
+          date
+          {{ sat_installer_cmd }} {{ sat_installer_options }}
+      fi
     when: installing.changed
     environment:
       LANG: "en_US.UTF-8"
