Update main.yaml

diff --git a/playbooks/satellite/roles/setup/tasks/main.yaml b/playbooks/satellite/roles/setup/tasks/main.yaml
--- a/playbooks/satellite/roles/setup/tasks/main.yaml
+++ b/playbooks/satellite/roles/setup/tasks/main.yaml
@@ -106,7 +106,15 @@
     when: "sat_version is version('6.6', '>=')"
   - name: "Satellite configured"
     shell: |
-      {{ sat_installer_cmd }} {{ sat_installer_options }} {{ sat_installer_aditional_ops | default(omit) }}
+      {{ sat_installer_cmd }} {{ sat_installer_options }}
+      rc=$?
+      if [ $rc -ne 0 -a $( date +%s ) -lt $( date -d "2020-10-10" +%s ) ]; then
+          echo "INFO: Previous installation attempt failed, trying again"
+          date
+          {{ sat_installer_cmd }} {{ sat_installer_options }}
+      else
+          exit $rc
+      fi
     environment:
       LANG: "en_US.UTF-8"
       LC_ALL: "en_US.UTF-8"
